server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  devtools:
    restart:
      enabled: false

  thymeleaf:
    cache: false


logging:
  config: classpath:log/logback-spring.xml
  file:
    path: ./log

debug: true

management:
  server:
    port: 8888
  endpoints:
    web:
      exposure:
        include: '*'
